### PR TITLE
Task254/303 - Configure application for data from Benefit-Service

### PR DESCRIPTION
**Pull request by will0684**
# Description 📝

This PR includes Redux configuration for consuming the data that the current Benefit-Service provides. The application now makes two requests for both languages and then stores both in separate maps in the application state. Language toggle is functional.

Note: This means the application will not work with the strapi endpoint anymore. Ensure the application's `benefitservice_env_url` is pointing to a valid instance of the updated Benefit-Service.

## Taiga Link 🔗

[Create landing page showing all available benefits according to data from benefit service ](https://taiga.dts-stn.com/project/ericdube-hfp-shared-backlog/task/254?kanban-status=130)

[Configure front end state management to work with separate french and english benefits data](https://taiga.dts-stn.com/project/ericdube-hfp-shared-backlog/task/303?kanban-status=130)

## Checklist ✅
- [ ] created story for all visual components
- [x ] created or modified necessary unit tests
- [ ] created or modified e2e tests
- [ ] modified README or any applicable documentation on the changes you made

### CODE REVIEW

**Review by shewood — APPROVED** [review]
Nice work Jordan.

**Review by DaceyTom2 — APPROVED** [review]
Looks good

**Review by var-kyle — APPROVED** [review]
LGTM

**Review by Moro-Code — APPROVED** [review]
Well done LGTM

**Pull request merged**
